### ISSUE TITLE
Added Content  approx as of document from Joachim

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/naiss_file_transfer_course#1]
It's a broad course as you see!

Do you think it is OK content?

What do you mean by "remove desktop environment"?

What shall we have as prereqs?

We shall probably formulate a logical text as well as advertisement.

**Comment by richelbilderbeek** [comment]
These are from Joachim? Here are my replies:

> Do you think it is OK content?

Yes, we use the documentation from the centers. We'll create exercises when we've had a green light on the learning objectives.


> What do you mean by "remove desktop environment"?

The same as [Wikipedia](https://en.wikipedia.org/wiki/Remote_desktop_software): a graphical environment (e.g. Ubuntu/Windows/etc) that is accessible remotely.

> What shall we have as prereqs?

An account at an HPC center.

> We shall probably formulate a logical text as well as advertisement.

If the learning objectives have gotten a green light, we can write an advertisement.

**Comment by bclaremar** [comment]
I got stuck with the word "remo**v**e" I tried but never connected it with "remo**t**e".

**Comment by richelbilderbeek** [comment]
Ah, silly me, I've overlooked the exact spelling :-) . Seems cleared up now anyways :+1:
