### ISSUE TITLE
Do we need a special session for 'VPN'?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/naiss_file_transfer_course#10]
The README has the structure as shown below, with 'VPN' as an item. Do we need to keep this?

## Curriculum overview

- Connecting through:
        [...]
- Special sessions
  -  [...]
  - VPN
   - [...]

**Comment by richelbilderbeek** [comment]
I vote no. Sure, some NAISS clusters require a VPN to access, so that is part of the log in session. Hence, I feel it does not need to be at a special session :+1:

**Comment by bclaremar** [comment]
No

**Comment by bclaremar** [comment]
no
