### ISSUE TITLE
Do we need a special session for 'Break-out for individual services?'

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/naiss_file_transfer_course#11]
The README has the structure as shown below, with 'Break-out for individual services? as an item. Do we need to keep this?

## Curriculum overview

- Connecting through:
        [...]
- Special sessions
  -  [...]
  - Break-out for individual services?

**Comment by richelbilderbeek** [comment]
I vote no, as I see no purpose yet, as the course is in its planning phase. If needed, I will surely suggest simultaneous sessions.

**Comment by bclaremar** [comment]
no
