### ISSUE TITLE
Dates for course days: Friday March 7th and others

### ISSUE THREAD

**Issue by bclaremar** [UPPMAX/naiss_file_transfer_course#15]
Input from Joachim:
•	Any proposal on how much time is need until you want to give a first run?
•	End of Q1 early Q2 and option?

**Comment by bclaremar** [comment]
My suggestion:
We are ready to give it in Feb/March/April.

I think that earlier the better, because most of (my/our) courses are, so far, in the second half (Q2)

**Comment by richelbilderbeek** [comment]
What about:
- Friday February 7th
- Thursdays February 13th
- Friday February 21st
- Friday February 28st
- Friday March 7st

I pick Friday to prevent us working in the weekends :-)

... but most dates are fine to me. Pick your favorite one or suggest one :+1:

**Comment by richelbilderbeek** [comment]
From BC:

Thanks!
Fri 7 Feb is a bit early for advertising
Thu 13 feb is Apptainer (are you involved?)
week 8-9 is Sportlov in many regions

Fri 7 March is best so far

**Comment by richelbilderbeek** [comment]
Fri 7 March it is!

![Screenshot from 2024-12-18 09-25-24](https://github.com/user-attachments/assets/b2f4ed31-d8ad-484f-8dce-6b7b7854fbc0)

**Comment by bclaremar** [comment]
Just got this from Joachim:

Thanks for the update.  The course should be offered 4 times per year.   Could you please add dates in Quarter 2, 3 and 4 as well?

I did not know 4 times was a requirement...

**Comment by richelbilderbeek** [comment]
What about:

- Friday May 16th (week 20)
- Friday Sep 5th (week 36)
- Friday Nov 5th (week 46)

Would work perfectly for me!

**Comment by bclaremar** [comment]
First 2 OK. I'll add those to shared doc 

week 46 is 10-14 Nov
5 Nov is Git course week (may work since probably different people)

**Comment by richelbilderbeek** [comment]
Friday 14 Nov (week 46) then

**Comment by richelbilderbeek** [comment]
Thanks to @jayant-yadav we know that Friday May 16th (week 20) is a bad day. What about use

Thursday May 15th (week 20)

instead?

**Comment by bclaremar** [comment]
The happening with IT was in the afternoon I believe and if we schedule 9-12 it is OK

**Comment by richelbilderbeek** [comment]
Friday May 16th 9:00-12:00 it is for the second iteration.

The fourth iteration is still open:

- ?Friday 14 Nov (week 46)

Would this work?

**Comment by bclaremar** [comment]
thumb up

**Comment by bclaremar** [comment]
Very clear!
👍
