### ISSUE TITLE
Vote teach basic Linux yes/no?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/naiss_file_transfer_course#3]
This course is about file transfer. This can be done with a familiar remote desktop environment, without much need of a terminal. 

Do we need to teach basic Linux regardless?

**Comment by richelbilderbeek** [comment]
I vote no.

**Comment by bclaremar** [comment]
I agree that we should limit teaching of linux commands but

you may need to orient yourself among the files

a list of good-to-know commands can at least be there

**Comment by richelbilderbeek** [comment]
If we teach rsysc (which seems to be getting to be the plan, #13), I will want to do file navigation too. For content, a link to a book, e.g. [The Linux Command Line](https://linuxcommand.org/lc3_lts0020.php) for the commands needed will work just fine for me.

**Comment by bclaremar** [comment]
Looks nice
Would that be prereq or part of the lessons?

**Comment by bclaremar** [comment]
alright!
part of lesson!

**Comment by richelbilderbeek** [comment]
I think we can conclude that we do not teach basic Linux as the current prereqs show:

> Be able to navigate the filesystem under Linux

Agreed?

If yes, this issue can be closed :+1:
