### ISSUE TITLE
Vote for how to connect

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/naiss_file_transfer_course#7]
The notes state:

- Connecting through:
  -  linux/mac terminals with ssh
  -  Windows tools with ssh
    - putty
    -   mobaxterm
  -  Thinlink
  -  VS-code (maybe too advanced)

How do we let our learners connect?

**Comment by richelbilderbeek** [comment]
In a fast meeting between me and @bclaremar we voted for using a remote desktop environment. It is already in the learning outcomes (see copy-paste below). The meeting was fast, so maybe another vote would be in place :-)

## Learning outcomes:

- log in to their center
    - Remove desktop environment using website (for example, as shown in [this UPPMAX page](https://docs.uppmax.uu.se/getting_started/login_rackham_remote_desktop_website/))
    - Remove desktop environment using local ThinLinc (for example, as shown in [this UPPMAX page](https://docs.uppmax.uu.se/getting_started/login_rackham_remote_desktop_local_thinlinc_client/))

**Comment by richelbilderbeek** [comment]
I vote to use:

- Remove desktop environment using website (for example, as shown in [this UPPMAX page](https://docs.uppmax.uu.se/getting_started/login_rackham_remote_desktop_website/))

If a center does not have this, then: 

- Remove desktop environment using local ThinLinc (for example, as shown in [this UPPMAX page](https://docs.uppmax.uu.se/getting_started/login_rackham_remote_desktop_local_thinlinc_client/))

Else, sure, SSH, is the only option.

**Comment by bclaremar** [comment]
I think we should cover all in some sense because it is a course about way**s** to connect and tranfer

**Comment by VRehnberg** [comment]
My opinion, cover:
 - SSH
 - Thinlinc
 
 how to deal with SSH for windows (WSL, PuTTY, ...?) I leave to you.

**Comment by richelbilderbeek** [comment]
Votes now:

- Website: Björn, Richel
- Local ThinLinc client: Björn, Richel, Viktor, 
- SSH: Björn, Richel, Viktor

Looking at #13, I think using local ThinLinc client and SSH will work fine with that :+1:

**Comment by bclaremar** [comment]
Some users have problems installing thinlinc themselves. That fact the some of the Centers has a web version is good to mention in the beginning of that session such that those users may follow. But that takes less than 5 minutes...

**Comment by richelbilderbeek** [comment]
What about we change the prereqs from what we have now:

> - Be able to login ** using a local ThinLinc client**
> - Be able to login using an SSH client
> - Be able to navigate the filesystem under Linux

to

> - Be able to login **to your cluster's remote desktop environment using either a website or a local ThinLinc client**
> - Be able to login using an SSH client
> - Be able to navigate the filesystem under Linux

?

**Comment by bclaremar** [comment]
Sounds good!
Let's do that!
