### ISSUE TITLE
What is 'Dardel needs to be sorted'?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/naiss_file_transfer_course#8]
In the README, there is now the structure as shown below. What does this mean that 'Dardel needs to be sorted'?

## Curriculum overview

- [...]
- Special sessions 
    - Dardel needs to be sorted 
    - [...]

**Comment by bclaremar** [comment]
the way to log in there is different from all other systems...

**Comment by richelbilderbeek** [comment]
Clear, thanks :+1:

Closing this issue :+1:
