### ISSUE TITLE
Do we need a special session for '2 factor authentication'?

### ISSUE THREAD

**Issue by richelbilderbeek** [UPPMAX/naiss_file_transfer_course#9]
The README has the structure as shown below, with '2 factor authentication' as an item. Do we need to keep this?

## Curriculum overview

- Connecting through:
    - [...]
- Special sessions 
    - [...]
    - 2 factor authentication 
    - [...]

**Comment by richelbilderbeek** [comment]
I vote no. Sure, 2FA is part of accessing some HPC centers, as part of accessing a cluster, so it would be part of a log in session at the start. But I feel it does not need a special session.

**Comment by bclaremar** [comment]
no
